name: Submission Tracker
description: Submit a new Topic Guide idea to DS Topic Guides.
title: "New Submission: [Please insert your draft Topic Guide Title here]"
labels: 'new Topic Guide submission/suggestion'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in contributing to DS Topic Guides! Please use this issue template to submit your Topic Guide proposal to the editorial team for consideration. Replace the text in brackets above with your Topic Guide title.  
  - type: textarea
    id: summary
    attributes:
      label: Topic Guide Proposal (Summary)
      description: Please briefly describe your Topic Guide idea here including the new Topic Guide's purpose and relevance to the work of library professionals.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: contributors
    attributes:
      label: Author Details
      description: Please specify the full Name, Email, Institution, and ORCID iDs of authors and co-authors to the Topic Guide.
      placeholder: Contributors to the Topic Guide.
      value: 
    validations:
      required: true
  - type: textarea
    id: liber-member
    attributes:
      label: Are at least one of the author's from a LIBER institution at the time of writing? 
      description: If not, we will pair you with a co-author from the LIBER network to ensure the European research library context is maintained. Please let us know if this is needed.
      placeholder: 
      value: 
    validations:
      required: true
  - type: textarea
    id: related-topics
    attributes:
      label: Related DS Topic Guides
      description: Are there any existing DS Topic Guides that may relate to/be referenced to your Topic Guide?
      placeholder: 
      value: 
    validations:
      required: true
  - type: checkboxes
    id: submission-checklist
    attributes:
      label: Submission Method
      description: Please select your preferred method for sharing your draft submission if accepted
      options:
        - label: GitHub Fork this repository, create a new guide using the existing QMD template https://github.com/libereurope/ds-topic-guides/blob/main/book/template.qmd and submit a pull request 
        - label: Google Doc Template https://docs.google.com/document/d/154zvn1mhghAddNqW0gJvKp9E8u2VLU8krnPo1wtm_Mk/edit?usp=sharing) and submit via email 
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any other comments?
      description: Please use the following text area to include any other notes or comments for the editors.  
      placeholder: 
      value: 
    validations:
      required: true
