name: Submission Tracker
description: Submit a new Topic Guide idea to DS Topic Guides.
title: "[SUBMISSION]: "
labels: 'new Topic Guide submission/suggestion'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in contributing to DS Topic Guides! Please use this template to submit your Topic Guide idea to the editorial team for consideration.  
  - type: textarea
    id: title
    attributes:
      label: Draft Title
      description: Please provide here a draft title for your Topic Guide
      placeholder: Title of the Topic Guide.
      value: <insert title here>
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Topic Guide Proposal (Summary)
      description: Please briefly describe your Topic Guide idea including the new Topic Guide's purpose and relevance to the work of library professionals.
      placeholder: Summary of the Topic Guide.
      value: <insert summary here>
    validations:
      required: true
  - type: textarea
    id: contributors
    attributes:
      label: Contributors
      description: Please specify the full names, emails, Institution, and ORCID iDs of contributors to the Topic Guide.
      placeholder: Contributors to the Topic Guide.
      value: 
    validations:
      required: true
  - type: input
    id: submission-date
    attributes:
      label: Submission Date
      description: Please specify the estimated date on which the first draft could be delivered.
      placeholder: Estimated date of first draft submission.
      value: <YYYY-MM-DD>
    validations:
      required: true
  - type: textarea
    id: related-topics
    attributes:
      label: Related Topics
      description: Are there any existing Topic Guides that may relate to/be referenced to your Topic Guide?
      placeholder: List any existing topic guides that may relate to/be referenced in some way.
      value: <1. Topic 1>
    validations:
      required: true
  - type: checkboxes
    id: submission-checklist
    attributes:
      label: Submission Method
      description: Please select your preferred method for sharing your draft submission
      options:
        - label: Happy to fork this repository
        - label: Please send a google template
        - label: No preference
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any other comments?
      description: Please use the following text area to include any other notes or comments for the editors.  
      placeholder: Notes and Comments.
      value: 
    validations:
      required: true
